### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by devforcactus** [devforcactus/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by illiapavlov93** [comment]
Personal life

2020
Quarantine has begun, it's lonely, I'm reviewing my old videos) I'm cool

2018
Moved to a new place, made 2 new friends (love them)

2017
Transplanted into a larger pot

2016
Bought in the store by strange people (turned out to be normal)

2015
Born (raised from the ground)

Career

2019

Starred in five episodes of the grossing film 'How Developers Work’ (3 main roles, 2 supporting roles)

Awards and honors

Best Actor in a Lead Role, for How Developers Work part 1(2019)

People's Choice Awards: Favorite Motion Picture Star in a How Developers Work part 2 (2019)

Golden Raspberry Award for Worst Supporting Actor for ow Developers Work part 4 (2019)

Binary Academy Student Choice Award (2019, 2020, 2021)
